Include /etc/nginx/modsecurity.conf
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsecurity/audit.jsonl
SecAuditLogFormat JSON
Include /etc/mwaf/active/main.conf
Include /usr/share/mwaf/crs/crs-setup.conf
Include /usr/share/mwaf/crs/rules/*.conf
