package manager

import "net/http"

func (s *Server) registerAdminRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /setup", s.setup)
	mux.HandleFunc("POST /setup", s.setup)
	mux.HandleFunc("GET /login", s.login)
	mux.HandleFunc("POST /login", s.login)
	mux.Handle("POST /logout", s.requireAdmin(http.HandlerFunc(s.logout)))
	mux.Handle("GET /account", s.requireAdmin(http.HandlerFunc(s.account)))
	mux.Handle("POST /account/password", s.requireAdmin(http.HandlerFunc(s.updateOwnPassword)))
	mux.Handle("GET /", s.requireAdmin(http.HandlerFunc(s.dashboard)))
	mux.Handle("GET /servers", s.requireAdmin(http.HandlerFunc(s.servers)))
	mux.Handle("GET /servers/{id}", s.requireAdmin(http.HandlerFunc(s.serverDetail)))
	mux.Handle("POST /servers/{id}/commands", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createServerCommand))))
	mux.Handle("POST /servers/{id}/packages", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.deployServerPackages))))
	mux.Handle("POST /servers/{id}/revoke", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.revokeServer))))
	mux.Handle("GET /events", s.requireAdmin(http.HandlerFunc(s.events)))
	mux.Handle("GET /policies", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.policies))))
	mux.Handle("GET /policies/new", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.newPolicy))))
	mux.Handle("POST /policies", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createPolicy))))
	mux.Handle("GET /policies/{id}", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.enterprisePolicyDetail))))
	mux.Handle("GET /policies/{id}/edit", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.editEnterprisePolicy))))
	mux.Handle("POST /policies/{id}/revisions", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createEnterprisePolicyRevision))))
	mux.Handle("POST /policies/{id}/strategy", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.updateEnterprisePolicyStrategy))))
	mux.Handle("POST /policies/{id}/convert", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.convertLegacyEnterprisePolicy))))
	mux.Handle("POST /policies/{id}/rollback", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.rollbackEnterprisePolicy))))
	mux.Handle("POST /policies/{id}/rollouts/{rollout_id}/approve", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.approveEnterprisePolicyRollout))))
	mux.Handle("POST /policies/{id}/rollouts/{rollout_id}/retry", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.retryEnterprisePolicyRollout))))
	mux.Handle("GET /system-policies", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.systemPolicies))))
	mux.Handle("GET /system-policies/migrations/new", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.newSystemPolicyMigration))))
	mux.Handle("POST /system-policies/migrations", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.publishSystemPolicyMigration))))
	mux.Handle("POST /system-policies/{id}/withdraw", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.withdrawSystemPolicyVersion))))
	mux.Handle("GET /open-source-policies", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.openSourcePolicies))))
	mux.Handle("POST /open-source-policies/sync", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.syncOpenSourcePolicies))))
	mux.Handle("GET /open-source-policies/{source_id}", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.openSourcePolicyDetail))))
	mux.Handle("GET /groups", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.groups))))
	mux.Handle("GET /groups/{id}", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.groupDetail))))
	mux.Handle("POST /groups", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createGroup))))
	mux.Handle("POST /groups/{id}", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.updateGroup))))
	mux.Handle("POST /groups/{id}/delete", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.deleteGroup))))
	mux.Handle("GET /enrollments/new", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.newEnrollment))))
	mux.Handle("POST /enrollments", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createEnrollment))))
	mux.Handle("POST /install-tokens", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createInstallToken))))
	mux.Handle("POST /install-tokens/{id}/revoke", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.revokeInstallToken))))
	mux.Handle("GET /enterprises", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.enterprises))))
	mux.Handle("GET /enterprises/{id}", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.enterpriseDetail))))
	mux.Handle("POST /enterprises", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.createEnterprise))))
	mux.Handle("POST /enterprises/{id}/delete", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.deleteEnterprise))))
	mux.Handle("GET /settings", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.systemSettings))))
	mux.Handle("GET /audit-logs", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.auditLogs))))
	mux.Handle("POST /settings", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.updateSystemSettings))))
	mux.Handle("GET /users", s.requireAdmin(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.users))))
	mux.Handle("POST /users", s.requireAdmin(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.createUser))))
	mux.Handle("GET /users/{id}", s.requireAdmin(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.editUser))))
	mux.Handle("POST /users/{id}", s.requireAdmin(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.updateUser))))
	mux.Handle("POST /users/{id}/delete", s.requireAdmin(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.deleteUser))))
}

func (s *Server) registerAdminAPIRoutes(mux *http.ServeMux) {
	mux.Handle("GET /api/v1/servers", s.requireAdmin(http.HandlerFunc(s.apiServers)))
	mux.Handle("GET /api/v1/overview", s.requireAdmin(http.HandlerFunc(s.apiOverview)))
	mux.Handle("GET /api/v1/events", s.requireAdmin(http.HandlerFunc(s.apiEvents)))
	mux.Handle("GET /api/v1/events/{id}", s.requireAdmin(http.HandlerFunc(s.apiEventDetail)))
	mux.Handle("POST /api/v1/policies/validate", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.apiValidatePolicy))))
	mux.Handle("GET /api/v1/open-source-policies", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicies))))
	mux.Handle("POST /api/v1/open-source-policies/sync", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiSyncOpenSourcePolicies))))
	mux.Handle("GET /api/v1/open-source-policies/{source_id}", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicy))))
	mux.Handle("GET /api/v1/open-source-policies/{source_id}/rules", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicyRules))))
	mux.Handle("GET /api/v1/open-source-policies/{source_id}/diff", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicyDiff))))
	mux.Handle("POST /api/v1/system-policy-migrations/validate", s.requireAdmin(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiValidateSystemPolicyMigration))))
	mux.Handle("POST /api/v1/enrollment-tokens", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.apiCreateEnrollment))))
	mux.Handle("POST /api/v1/enterprise-install-tokens", s.requireAdmin(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.apiCreateInstallToken))))
}
