package manager

import "net/http"

func (s *Server) registerAdminRoutes(mux *http.ServeMux) {
	admin := func(handler http.Handler) http.Handler { return s.requireAdmin(handler) }
	account := func(handler http.Handler) http.Handler { return admin(s.requireAccountConsole(handler)) }
	enterprise := func(handler http.Handler) http.Handler { return admin(s.requireEnterpriseConsole(handler)) }
	system := func(handler http.Handler) http.Handler { return admin(s.requireSystemConsole(handler)) }

	mux.HandleFunc("GET /setup", s.setup)
	mux.HandleFunc("POST /setup", s.setup)
	mux.HandleFunc("GET /login", s.login)
	mux.HandleFunc("POST /login", s.login)
	mux.Handle("POST /logout", admin(http.HandlerFunc(s.logout)))
	mux.Handle("GET /account", account(http.HandlerFunc(s.account)))
	mux.Handle("POST /account/password", account(http.HandlerFunc(s.updateOwnPassword)))
	mux.Handle("GET /", enterprise(http.HandlerFunc(s.dashboard)))
	mux.Handle("GET /reports", enterprise(http.HandlerFunc(s.reports)))
	mux.Handle("GET /servers", enterprise(http.HandlerFunc(s.servers)))
	mux.Handle("GET /servers/{id}", enterprise(http.HandlerFunc(s.serverDetail)))
	mux.Handle("POST /servers/{id}/commands", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createServerCommand))))
	mux.Handle("POST /servers/{id}/packages", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.deployServerPackages))))
	mux.Handle("POST /servers/{id}/installation", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.installServerModule))))
	mux.Handle("POST /servers/{id}/revoke", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.revokeServer))))
	mux.Handle("GET /events", enterprise(http.HandlerFunc(s.events)))
	mux.Handle("GET /policies", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.policies))))
	mux.Handle("GET /policies/new", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.newPolicy))))
	mux.Handle("POST /policies", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createPolicy))))
	mux.Handle("GET /policies/{id}", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.enterprisePolicyDetail))))
	mux.Handle("GET /policies/{id}/edit", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.editEnterprisePolicy))))
	mux.Handle("POST /policies/{id}/revisions", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createEnterprisePolicyRevision))))
	mux.Handle("POST /policies/{id}/servers", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.updateEnterprisePolicyServers))))
	mux.Handle("POST /policies/{id}/strategy", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.updateEnterprisePolicyStrategy))))
	mux.Handle("POST /policies/{id}/convert", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.convertLegacyEnterprisePolicy))))
	mux.Handle("POST /policies/{id}/rollback", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.rollbackEnterprisePolicy))))
	mux.Handle("POST /policies/{id}/rollouts/{rollout_id}/approve", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.approveEnterprisePolicyRollout))))
	mux.Handle("POST /policies/{id}/rollouts/{rollout_id}/retry", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.retryEnterprisePolicyRollout))))
	mux.Handle("POST /policies/{id}/exceptions/from-incident", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createIncidentException))))
	mux.Handle("POST /policies/{id}/ip-rules", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createPolicyIPRule))))
	mux.Handle("POST /policies/{id}/ip-rules/{rule_id}/delete", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.deletePolicyIPRule))))
	mux.Handle("GET /ip-rules", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.ipRules))))
	mux.Handle("GET /groups", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.legacyGroupsRedirect))))
	mux.Handle("GET /groups/{id}", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.legacyGroupsRedirect))))
	mux.Handle("GET /enrollments/new", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.newEnrollment))))
	mux.Handle("POST /enrollments", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createEnrollment))))
	mux.Handle("POST /install-tokens", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.createInstallToken))))
	mux.Handle("POST /install-tokens/{id}/revoke", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.revokeInstallToken))))
	mux.Handle("GET /users", enterprise(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.users))))
	mux.Handle("POST /users", enterprise(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.createUser))))
	mux.Handle("GET /users/{id}", enterprise(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.editUser))))
	mux.Handle("POST /users/{id}", enterprise(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.updateUser))))
	mux.Handle("POST /users/{id}/delete", enterprise(s.requireRole(RoleEnterpriseAdmin, http.HandlerFunc(s.deleteUser))))

	mux.Handle("GET /system-policies", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.systemPolicies))))
	mux.Handle("GET /system-policies/migrations/new", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.newSystemPolicyMigration))))
	mux.Handle("POST /system-policies/migrations", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.publishSystemPolicyMigration))))
	mux.Handle("GET /system-policies/{id}/adoptions", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.systemPolicyAdoptions))))
	mux.Handle("POST /system-policies/{id}/withdraw", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.withdrawSystemPolicyVersion))))
	mux.Handle("GET /open-source-policies", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.openSourcePolicies))))
	mux.Handle("POST /open-source-policies/sync", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.syncOpenSourcePolicies))))
	mux.Handle("GET /open-source-policies/{source_id}", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.openSourcePolicyDetail))))
	mux.Handle("GET /enterprises", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.enterprises))))
	mux.Handle("GET /enterprises/{id}", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.enterpriseDetail))))
	mux.Handle("POST /enterprises", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.createEnterprise))))
	mux.Handle("POST /enterprises/{id}/delete", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.deleteEnterprise))))
	mux.Handle("GET /enterprises/{enterprise_id}/users", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.users))))
	mux.Handle("POST /enterprises/{enterprise_id}/users", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.createUser))))
	mux.Handle("GET /enterprises/{enterprise_id}/users/{user_id}", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.editUser))))
	mux.Handle("POST /enterprises/{enterprise_id}/users/{user_id}", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.updateUser))))
	mux.Handle("POST /enterprises/{enterprise_id}/users/{user_id}/delete", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.deleteUser))))
	mux.Handle("GET /settings", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.systemSettings))))
	mux.Handle("GET /audit-logs", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.auditLogs))))
	mux.Handle("POST /settings", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.updateSystemSettings))))
}

func (s *Server) registerAdminAPIRoutes(mux *http.ServeMux) {
	enterprise := func(handler http.Handler) http.Handler { return s.requireAdmin(s.requireEnterpriseConsole(handler)) }
	system := func(handler http.Handler) http.Handler { return s.requireAdmin(s.requireSystemConsole(handler)) }
	mux.Handle("GET /api/v1/servers", enterprise(http.HandlerFunc(s.apiServers)))
	mux.Handle("GET /api/v1/overview", enterprise(http.HandlerFunc(s.apiOverview)))
	mux.Handle("GET /api/v1/events", enterprise(http.HandlerFunc(s.apiEvents)))
	mux.Handle("GET /api/v1/events/{id}", enterprise(http.HandlerFunc(s.apiEventDetail)))
	mux.Handle("GET /api/v1/incidents", enterprise(http.HandlerFunc(s.apiIncidents)))
	mux.Handle("GET /api/v1/incidents/{id}", enterprise(http.HandlerFunc(s.apiIncidentDetail)))
	mux.Handle("POST /api/v1/policies/validate", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.apiValidatePolicy))))
	mux.Handle("GET /api/v1/open-source-policies", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicies))))
	mux.Handle("POST /api/v1/open-source-policies/sync", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiSyncOpenSourcePolicies))))
	mux.Handle("GET /api/v1/open-source-policies/{source_id}", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicy))))
	mux.Handle("GET /api/v1/open-source-policies/{source_id}/file", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicyFile))))
	mux.Handle("GET /api/v1/open-source-policies/{source_id}/rules", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicyRules))))
	mux.Handle("GET /api/v1/open-source-policies/{source_id}/diff", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiOpenSourcePolicyDiff))))
	mux.Handle("POST /api/v1/system-policy-migrations/validate", system(s.requireRole(RoleSystemAdmin, http.HandlerFunc(s.apiValidateSystemPolicyMigration))))
	mux.Handle("POST /api/v1/enrollment-tokens", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.apiCreateEnrollment))))
	mux.Handle("POST /api/v1/enterprise-install-tokens", enterprise(s.requireRole(RoleEnterpriseUser, http.HandlerFunc(s.apiCreateInstallToken))))
}
